GET http://localhost:3000/users/24?limit=20&page=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoidGVzdDMyQGdtYWlsLmNvbSIsImlhdCI6MTc2NTk1NDg2NCwiZXhwIjoxNzY1OTU4NDY0LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.1cxb3EiJggbDphMwzqzTR1APsN5HGn67mAnGncOt3jI